# Generated by Django 3.2.6 on 2021-08-23 14:49

import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trivia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now_add=True)),
                ('pregunta_enunciado', models.TextField(max_length=100)),
                ('dato', models.TextField(max_length=600)),
                ('puntos', models.PositiveIntegerField(default=5)),
                ('imagen', models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='D:\\Desarrollo\\Python\\Informatorio\\media'), upload_to='')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categoria', to='trivia.categoria')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Respuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now_add=True)),
                ('respuesta_enunciado', models.CharField(max_length=100)),
                ('correcta', models.BooleanField(default=False)),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pregunta', to='preguntas.pregunta')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
