# Generated by Django 3.2.6 on 2021-08-26 01:13

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preguntas', '0002_alter_pregunta_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pregunta',
            name='imagen',
            field=models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='C:\\LUCIO\\_PregunChaco2\\media'), upload_to=''),
        ),
    ]
