# Generated by Django 3.2.6 on 2021-08-23 14:49

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now_add=True)),
                ('nombre_categoria', models.CharField(max_length=100)),
                ('logo_categoria', models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='D:\\Desarrollo\\Python\\Informatorio\\media'), upload_to='')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
