# Generated by Django 3.2.6 on 2021-08-28 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_rename_usuario_perfil_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Perfil',
        ),
    ]
