# Generated by Django 3.2.6 on 2021-09-02 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_alter_perfil_imagen_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='perfil',
            name='first_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='last_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
