# Generated by Django 3.2.6 on 2021-09-02 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0009_auto_20210901_2159'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='username',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
