# Generated by Django 3.2.6 on 2021-09-02 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0010_perfil_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='password',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
