# Generated by Django 3.2.6 on 2021-08-26 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resultado', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='puntaje',
            old_name='trivia',
            new_name='categoria',
        ),
        migrations.RenameField(
            model_name='puntaje',
            old_name='score',
            new_name='puntaje',
        ),
    ]
