# Generated by Django 3.2.6 on 2021-08-27 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resultado', '0002_auto_20210826_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puntaje',
            name='categoria',
            field=models.CharField(max_length=20),
        ),
    ]
